name = "workers-sdk-rag"
compatibility_date = "2022-05-03"
main = "src/index.ts"

[[vectorize]]
binding = "WORKERS_SDK_RAG_INDEX"
index_name = "workers-sdk-rag"

[ai]
binding = "WORKERS_SDK_RAG_AI"

[[kv_namespaces]]
binding = "WORKERS_SDK_RAG_KV"
id = "03690cb14727424d8e5605c6b3f159b7"

[[durable_objects.bindings]]
name = "WORKERS_SDK_CONSISTENT_KV"
class_name = "ConsistentKVDO"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ConsistentKVDO"]